#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jsonassert
Version  : 1.3.0
Release  : 3
URL      : https://github.com/skyscreamer/JSONassert/archive/jsonassert-1.3.0.tar.gz
Source0  : https://github.com/skyscreamer/JSONassert/archive/jsonassert-1.3.0.tar.gz
Source1  : https://repo1.maven.org/maven2/org/skyscreamer/jsonassert/1.3.0/jsonassert-1.3.0.jar
Source2  : https://repo1.maven.org/maven2/org/skyscreamer/jsonassert/1.3.0/jsonassert-1.3.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jsonassert-data = %{version}-%{release}

%description
JSONassert
==========
Write JSON unit tests in less code.  Great for testing REST interfaces.

%package data
Summary: data components for the mvn-jsonassert package.
Group: Data

%description data
data components for the mvn-jsonassert package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/skyscreamer/jsonassert/1.3.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/skyscreamer/jsonassert/1.3.0/jsonassert-1.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/skyscreamer/jsonassert/1.3.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/skyscreamer/jsonassert/1.3.0/jsonassert-1.3.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/skyscreamer/jsonassert/1.3.0/jsonassert-1.3.0.jar
/usr/share/java/.m2/repository/org/skyscreamer/jsonassert/1.3.0/jsonassert-1.3.0.pom
